import { getApps, getApp, initializeApp } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, updateDoc, runTransaction, increment, deleteField, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js';

const VERSION='36.11.0';
const firebaseConfig={apiKey:'AIzaSyAExc0XnqS2MjL3bTmvNNx2CnBbziiyJds',authDomain:'elo-app-82e6e.firebaseapp.com',projectId:'elo-app-82e6e',storageBucket:'elo-app-82e6e.firebasestorage.app',messagingSenderId:'107299510923',appId:'1:107299510923:web:eb9c8b550ba4ecb3bc528e'};
const app=getApps().length?getApp():initializeApp(firebaseConfig);
const auth=getAuth(app),db=getFirestore(app);
const state={user:null,isAdmin:false,adminDoc:null,themeSignature:'',themeReady:false,comets:new Map(),raf:0,lastFrame:0};
window.ELO_V36_11={version:VERSION,isAdmin:false};

const css=document.createElement('style');
css.textContent=`
#elo-admin-fab{position:fixed;right:14px;top:max(14px,env(safe-area-inset-top));z-index:2147483000;border:1px solid rgba(251,113,133,.45);background:rgba(15,23,42,.94);color:#fff;padding:9px 12px;border-radius:999px;font:900 10px/1 Inter,sans-serif;letter-spacing:.08em;box-shadow:0 12px 34px rgba(0,0,0,.4);backdrop-filter:blur(14px)}
#elo-admin-fab span{color:#fb7185}.elo-admin-overlay{position:fixed;inset:0;z-index:2147483500;background:rgba(2,6,23,.82);backdrop-filter:blur(12px);display:grid;place-items:end center;padding:12px}.elo-admin-panel{width:min(100%,460px);max-height:88dvh;overflow:auto;background:#0f172a;border:1px solid rgba(148,163,184,.2);border-radius:26px;padding:18px;color:#e2e8f0;box-shadow:0 28px 80px rgba(0,0,0,.55)}.elo-admin-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.elo-admin-head h2{font-size:18px;font-weight:900;color:white}.elo-admin-badge{display:inline-flex;padding:5px 8px;border-radius:999px;background:rgba(244,63,94,.13);color:#fb7185;font-size:9px;font-weight:900;letter-spacing:.12em}.elo-admin-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.elo-admin-btn{border:1px solid rgba(148,163,184,.16);background:#1e293b;color:white;border-radius:14px;padding:11px 10px;font-size:11px;font-weight:900}.elo-admin-btn:active{transform:scale(.97)}.elo-admin-btn.danger{border-color:rgba(244,63,94,.3);background:rgba(127,29,29,.22);color:#fecdd3}.elo-admin-btn.good{border-color:rgba(34,197,94,.28);background:rgba(20,83,45,.24);color:#bbf7d0}.elo-admin-section{padding:13px 0;border-top:1px solid rgba(148,163,184,.12)}.elo-admin-section:first-of-type{border-top:0}.elo-admin-section h3{font-size:10px;text-transform:uppercase;letter-spacing:.14em;color:#94a3b8;font-weight:900;margin-bottom:8px}.elo-admin-note{font-size:10px;color:#94a3b8;line-height:1.55}.elo-admin-input{width:100%;background:#020617;border:1px solid #334155;border-radius:12px;padding:11px;color:white;margin-bottom:8px}.elo-admin-sandbox::after{content:'MODO ADM';position:fixed;left:50%;top:max(8px,env(safe-area-inset-top));transform:translateX(-50%);z-index:2147482500;background:rgba(225,29,72,.9);color:#fff;padding:5px 9px;border-radius:999px;font:900 9px/1 Inter,sans-serif;letter-spacing:.14em;pointer-events:none}.elo-theme-celestial .elo-space-comet{animation:none!important;will-change:transform,opacity;transform-origin:center center}.elo-theme-celestial .elo-space-comet::before,.elo-theme-celestial .elo-space-comet::after{transform-origin:right center!important}.elo-theme-celestial #elo-theme-fx{overflow:hidden}
`;
document.head.appendChild(css);

const toast=(text,type='info')=>{try{if(typeof window.showToast==='function')return window.showToast(text,type)}catch(_){} console.log('[Elo V36.11]',text)};
const uid=()=>state.user?.uid||'';
const coupleId=()=>window.coupleId||localStorage.getItem('elo_coupleId')||'';
const ownedKey=()=>`elo_theme_owned_${uid()||'device'}`;
const themeKey=()=>`elo_theme_${uid()||'device'}`;
const safeOwned=()=>{try{return [...new Set(['akai',...JSON.parse(localStorage.getItem(ownedKey())||'[]')])]}catch(_){return ['akai']}};
const saveLocalAppearance=(appearance={})=>{const owned=[...new Set(['akai',...(Array.isArray(appearance.ownedThemes)?appearance.ownedThemes:[])])];localStorage.setItem(ownedKey(),JSON.stringify(owned.filter(x=>x!=='akai')));const selected=owned.includes(appearance.themeId)?appearance.themeId:'akai';localStorage.setItem(themeKey(),selected)};
const appearanceNow=()=>({ownedThemes:safeOwned(),themeId:localStorage.getItem(themeKey())||'akai'});
const appearanceSig=a=>JSON.stringify({ownedThemes:[...(a.ownedThemes||[])].sort(),themeId:a.themeId||'akai'});

async function initThemeSync(user){
 const ref=doc(db,'userProfiles',user.uid); const snap=await getDoc(ref); const data=snap.exists()?snap.data():{}; const cloud=data.appearance;
 if(cloud&&Array.isArray(cloud.ownedThemes)) saveLocalAppearance(cloud);
 else {const local=appearanceNow();await setDoc(ref,{appearance:{...local,syncedAt:Date.now()}},{merge:true});}
 state.themeSignature=appearanceSig(appearanceNow());state.themeReady=true;
}
async function pollThemeSync(){
 if(!state.user||!state.themeReady)return;const current=appearanceNow();const sig=appearanceSig(current);if(sig===state.themeSignature)return;state.themeSignature=sig;
 try{await setDoc(doc(db,'userProfiles',uid()),{appearance:{...current,syncedAt:Date.now()}},{merge:true});}catch(e){console.warn('V36.11 theme sync',e)}
}

function addAdminFab(){if(document.getElementById('elo-admin-fab'))return;const b=document.createElement('button');b.id='elo-admin-fab';b.innerHTML='<span>◆</span> ADM';b.onclick=openAdminPanel;document.body.appendChild(b)}
function removeAdminFab(){document.getElementById('elo-admin-fab')?.remove();document.getElementById('elo-admin-overlay')?.remove();document.body.classList.remove('elo-admin-sandbox')}
const isSandbox=()=>!!coupleId()&&coupleId()===`__admin_${uid()}`;

async function checkAdmin(user){
 try{const s=await getDoc(doc(db,'admins',user.uid));state.isAdmin=!!(s.exists()&&s.data()?.enabled===true);state.adminDoc=s.exists()?s.data():null;}catch(e){state.isAdmin=false;state.adminDoc=null;console.warn('ADM indisponível:',e)}
 window.ELO_V36_11.isAdmin=state.isAdmin;if(state.isAdmin){addAdminFab();if(isSandbox())document.body.classList.add('elo-admin-sandbox');installMissionHook()}else removeAdminFab();
}

function adminHtml(){return `<div id="elo-admin-overlay" class="elo-admin-overlay" onclick="if(event.target===this)this.remove()"><div class="elo-admin-panel"><div class="elo-admin-head"><div><span class="elo-admin-badge">SANDBOX DE DESENVOLVIMENTO</span><h2>Painel ADM · Elo V${VERSION}</h2></div><button class="elo-admin-btn" onclick="document.getElementById('elo-admin-overlay')?.remove()">Fechar</button></div><p class="elo-admin-note">UID: ${uid()}<br>Elo atual: ${coupleId()||'nenhum'} ${isSandbox()?'· SANDBOX':''}</p><div class="elo-admin-section"><h3>Sandbox solo</h3><div class="elo-admin-grid"><button class="elo-admin-btn good" onclick="eloAdminEnterSandbox()">Entrar no Sandbox</button><button class="elo-admin-btn" onclick="eloAdminExitSandbox()">Voltar ao Elo real</button></div></div><div class="elo-admin-section"><h3>Elo Coins</h3><input id="elo-admin-coins" class="elo-admin-input" type="number" inputmode="numeric" placeholder="Valor personalizado, ex.: 500"><div class="elo-admin-grid"><button class="elo-admin-btn good" onclick="eloAdminCoins(100)">+100</button><button class="elo-admin-btn good" onclick="eloAdminCoins(1000)">+1000</button><button class="elo-admin-btn danger" onclick="eloAdminCoins(-100)">-100</button><button class="elo-admin-btn danger" onclick="eloAdminCoins(-1000)">-1000</button></div><button class="elo-admin-btn" style="width:100%;margin-top:8px" onclick="eloAdminCoins(Number(document.getElementById('elo-admin-coins')?.value||0))">Aplicar valor</button></div><div class="elo-admin-section"><h3>Testes e limpeza</h3><div class="elo-admin-grid"><button class="elo-admin-btn" onclick="eloAdminResetThemes()">Resetar temas para Akai</button><button class="elo-admin-btn danger" onclick="eloAdminResetPet()">Remover Pets deste Elo</button></div><p class="elo-admin-note" style="margin-top:8px">No Sandbox, missões marcadas como concluídas são autoaprovadas para sua própria conta.</p></div></div></div>`}
function openAdminPanel(){if(!state.isAdmin)return;document.getElementById('elo-admin-overlay')?.remove();document.body.insertAdjacentHTML('beforeend',adminHtml())}
window.openEloAdmin=openAdminPanel;

window.eloAdminCoins=async delta=>{if(!state.isAdmin||!Number.isFinite(delta)||delta===0)return;const cid=coupleId();if(!cid)return toast('Entre em um Elo ou no Sandbox.','error');try{await updateDoc(doc(db,'relationships',cid),{[`users.${uid()}.coins`]:increment(Math.trunc(delta))});toast(`${delta>0?'+':''}${Math.trunc(delta)} Elo Coins aplicado.`,'success')}catch(e){console.error(e);toast('Não foi possível alterar as moedas.','error')}};
window.eloAdminEnterSandbox=async()=>{if(!state.isAdmin)return;const user=state.user,sid=`__admin_${user.uid}`;try{const pRef=doc(db,'userProfiles',user.uid),pSnap=await getDoc(pRef),profile=pSnap.exists()?pSnap.data():{},previous=profile.adminSandbox?.previousCoupleId||profile.coupleId||localStorage.getItem('elo_coupleId')||'';await setDoc(doc(db,'relationships',sid),{isAdminSandbox:true,adminOwnerUid:user.uid,createdAt:Date.now(),users:{[user.uid]:{name:user.displayName||'ADM',email:user.email||'',photoUrl:user.photoURL||'',coins:10000,xp:0,streak:0}},quests:{}},{merge:true});await setDoc(pRef,{coupleId:sid,adminSandbox:{active:true,previousCoupleId:previous,updatedAt:Date.now()}},{merge:true});localStorage.setItem('elo_coupleId',sid);location.reload()}catch(e){console.error(e);toast('Não foi possível abrir o Sandbox. Verifique as regras do Firestore.','error')}};
window.eloAdminExitSandbox=async()=>{if(!state.isAdmin)return;try{const ref=doc(db,'userProfiles',uid()),snap=await getDoc(ref),profile=snap.data()||{},previous=profile.adminSandbox?.previousCoupleId||'';const updates={'adminSandbox.active':false,'adminSandbox.updatedAt':Date.now()};updates.coupleId=previous||deleteField();await updateDoc(ref,updates);if(previous)localStorage.setItem('elo_coupleId',previous);else localStorage.removeItem('elo_coupleId');location.reload()}catch(e){console.error(e);toast('Não foi possível sair do Sandbox.','error')}};
window.eloAdminResetThemes=async()=>{if(!state.isAdmin)return;if(!confirm('Remover todos os temas comprados desta conta e voltar ao Akai?'))return;const appearance={ownedThemes:['akai'],themeId:'akai',syncedAt:Date.now(),resetByAdmin:true};try{saveLocalAppearance(appearance);state.themeSignature=appearanceSig(appearance);await setDoc(doc(db,'userProfiles',uid()),{appearance},{merge:true});toast('Temas de teste removidos. Reabra o Elo para aplicar em todas as telas.','success')}catch(e){console.error(e);toast('Falha ao resetar temas.','error')}};
window.eloAdminResetPet=async()=>{if(!state.isAdmin)return;const cid=coupleId();if(!cid)return;if(!confirm('Isso removerá Pet ativo e coleção de Pets deste Elo. Continuar?'))return;try{await updateDoc(doc(db,'relationships',cid),{pet:deleteField(),petActiveId:deleteField(),petCollection:{}});toast('Pets removidos deste Elo.','success')}catch(e){console.error(e);toast('Não foi possível remover os Pets.','error')}};

function missionRewardFromDom(questId){for(const el of document.querySelectorAll('[onclick]')){const a=el.getAttribute('onclick')||'';if(!a.includes(questId))continue;let card=el;for(let i=0;i<6&&card;i++,card=card.parentElement){const t=card.innerText||'';const c=t.match(/\+(\d+)\s*Coins/i),x=t.match(/\+(\d+)\s*XP/i);if(c||x)return{reward:Number(c?.[1]||0),xp:Number(x?.[1]||0)}}}return{reward:0,xp:0}}
async function autoApproveMission(questId,reward,xp){if(!state.isAdmin||!isSandbox())return;const cid=coupleId(),key=`${questId}_${uid()}`;try{await new Promise(r=>setTimeout(r,180));await runTransaction(db,async tx=>{const ref=doc(db,'relationships',cid),snap=await tx.get(ref);if(!snap.exists())return;const d=snap.data();if(d.quests?.[key]!=='pending_approval')return;tx.update(ref,{[`quests.${key}`]:'completed',[`users.${uid()}.coins`]:increment(reward),[`users.${uid()}.xp`]:increment(xp)})});toast(`Missão autoaprovada${reward?` · +${reward} Coins`:''}.`,'success')}catch(e){console.warn('Autoaprovação ADM:',e)}}
function installMissionHook(){if(window.__eloAdminMissionHook)return;const timer=setInterval(()=>{if(!state.isAdmin)return;if(typeof window.confirmQuestCompletion!=='function')return;clearInterval(timer);if(window.__eloAdminMissionHook)return;const original=window.confirmQuestCompletion.bind(window);window.confirmQuestCompletion=async questId=>{const rx=missionRewardFromDom(questId);const result=await original(questId);if(isSandbox())autoApproveMission(questId,rx.reward,rx.xp);return result};window.__eloAdminMissionHook=true},500)}

function resetComet(el,index){const w=innerWidth,h=innerHeight,fromLeft=Math.random()>.35;const y=h*(.08+Math.random()*.68);const speed=95+Math.random()*70;const angle=(Math.random()-.5)*.22;const x=fromLeft?-90:w+90;const vx=(fromLeft?1:-1)*speed*Math.cos(angle),vy=speed*Math.sin(angle);state.comets.set(el,{x,y,vx,vy,index,seed:Math.random()*10});el.style.animation='none';el.style.opacity='.82'}
function cometFrame(now){state.raf=requestAnimationFrame(cometFrame);if(!document.body.classList.contains('elo-theme-celestial')){state.comets.clear();state.lastFrame=now;return}const hole=document.querySelector('.elo-black-hole'),els=[...document.querySelectorAll('.elo-space-comet')];if(!hole||!els.length){state.lastFrame=now;return}const hr=hole.getBoundingClientRect(),hx=hr.left+hr.width/2,hy=hr.top+hr.height/2;const dt=Math.min(.035,Math.max(.008,(now-(state.lastFrame||now))/1000));state.lastFrame=now;els.forEach((el,i)=>{if(!state.comets.has(el))resetComet(el,i);const p=state.comets.get(el);let dx=hx-p.x,dy=hy-p.y,r2=dx*dx+dy*dy,dist=Math.sqrt(r2)||1;const soft=95,G=720000;let a=G/(r2+soft*soft);a=Math.min(a,250);p.vx+=a*(dx/dist)*dt;p.vy+=a*(dy/dist)*dt;const speed=Math.hypot(p.vx,p.vy);if(speed>330){p.vx=p.vx/speed*330;p.vy=p.vy/speed*330}p.x+=p.vx*dt;p.y+=p.vy*dt;const ang=Math.atan2(p.vy,p.vx)*180/Math.PI;const stretch=Math.max(1,Math.min(1.9,1+(220-Math.min(220,dist))/240));el.style.transform=`translate3d(${p.x}px,${p.y}px,0) rotate(${ang}deg) scaleX(${stretch})`;el.style.opacity=String(Math.max(.24,Math.min(1,.58+speed/520)));if(dist<Math.max(28,hr.width*.12)||p.x<-180||p.x>innerWidth+180||p.y<-160||p.y>innerHeight+160)resetComet(el,i)})}
if(!matchMedia('(prefers-reduced-motion: reduce)').matches)state.raf=requestAnimationFrame(cometFrame);

onAuthStateChanged(auth,async user=>{state.user=user;state.themeReady=false;if(!user){removeAdminFab();return}try{await initThemeSync(user)}catch(e){console.warn('Theme sync init:',e)}await checkAdmin(user)});
setInterval(pollThemeSync,1200);
console.info(`[Elo] V${VERSION} runtime carregado.`);
