import { getApps, getApp, initializeApp } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, updateDoc, runTransaction, increment, deleteField, onSnapshot, collection, query, orderBy, limit, getDocs } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js';

const VERSION='36.11.6';
const firebaseConfig={apiKey:'AIzaSyAExc0XnqS2MjL3bTmvNNx2CnBbziiyJds',authDomain:'elo-app-82e6e.firebaseapp.com',projectId:'elo-app-82e6e',storageBucket:'elo-app-82e6e.firebasestorage.app',messagingSenderId:'107299510923',appId:'1:107299510923:web:eb9c8b550ba4ecb3bc528e'};
const app=getApps().length?getApp():initializeApp(firebaseConfig);
const auth=getAuth(app),db=getFirestore(app);
const state={user:null,isAdmin:false,adminDoc:null,themeSignature:'',themeReady:false,profileUnsub:null,comets:new Map(),raf:0,lastFrame:0,lastPaint:0,petSyncQueued:false,gameHooks:false,missionHooks:false,uiHooks:false,navHooks:false,profileHooks:false,domTuneQueued:false,scrollBusyTimer:0};
window.ELO_V36_11={version:VERSION,isAdmin:false};
window.ELO_FLUIDITY={version:VERSION,phase:2,lowEnd:false};

const lowEndDevice=(()=>{const cores=Number(navigator.hardwareConcurrency||4),memory=Number(navigator.deviceMemory||4);return cores<=4||memory<=4})();
window.ELO_FLUIDITY.lowEnd=lowEndDevice;
if(lowEndDevice)document.documentElement.classList.add('elo-lite-device');
function afterBody(fn){if(document.body)fn();else document.addEventListener('DOMContentLoaded',fn,{once:true})}
afterBody(()=>document.body.classList.add('elo-pet-ui-guard'));

const css=document.createElement('style');
css.textContent=`
#elo-admin-fab{position:fixed;right:14px;top:max(14px,env(safe-area-inset-top));z-index:2147483000;border:1px solid rgba(251,113,133,.45);background:rgba(15,23,42,.94);color:#fff;padding:9px 12px;border-radius:999px;font:900 10px/1 Inter,sans-serif;letter-spacing:.08em;box-shadow:0 12px 34px rgba(0,0,0,.4);backdrop-filter:blur(10px)}
#elo-admin-fab span{color:#fb7185}.elo-admin-overlay{position:fixed;inset:0;z-index:2147483500;background:rgba(2,6,23,.82);backdrop-filter:blur(8px);display:grid;place-items:end center;padding:12px}.elo-admin-panel{width:min(100%,460px);max-height:88dvh;overflow:auto;background:#0f172a;border:1px solid rgba(148,163,184,.2);border-radius:26px;padding:18px;color:#e2e8f0;box-shadow:0 28px 80px rgba(0,0,0,.55)}.elo-admin-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.elo-admin-head h2{font-size:18px;font-weight:900;color:white}.elo-admin-badge{display:inline-flex;padding:5px 8px;border-radius:999px;background:rgba(244,63,94,.13);color:#fb7185;font-size:9px;font-weight:900;letter-spacing:.12em}.elo-admin-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.elo-admin-btn{border:1px solid rgba(148,163,184,.16);background:#1e293b;color:white;border-radius:14px;padding:11px 10px;font-size:11px;font-weight:900}.elo-admin-btn:active{transform:scale(.97)}.elo-admin-btn.danger{border-color:rgba(244,63,94,.3);background:rgba(127,29,29,.22);color:#fecdd3}.elo-admin-btn.good{border-color:rgba(34,197,94,.28);background:rgba(20,83,45,.24);color:#bbf7d0}.elo-admin-section{padding:13px 0;border-top:1px solid rgba(148,163,184,.12)}.elo-admin-section:first-of-type{border-top:0}.elo-admin-section h3{font-size:10px;text-transform:uppercase;letter-spacing:.14em;color:#94a3b8;font-weight:900;margin-bottom:8px}.elo-admin-note{font-size:10px;color:#94a3b8;line-height:1.55}.elo-admin-input{width:100%;background:#020617;border:1px solid #334155;border-radius:12px;padding:11px;color:white;margin-bottom:8px}.elo-admin-sandbox::after{content:'MODO ADM';position:fixed;left:50%;top:max(8px,env(safe-area-inset-top));transform:translateX(-50%);z-index:2147482500;background:rgba(225,29,72,.9);color:#fff;padding:5px 9px;border-radius:999px;font:900 9px/1 Inter,sans-serif;letter-spacing:.14em;pointer-events:none}
.elo-pet-ui-guard .elo-floating-pet,.elo-pet-ui-guard .elo-pet-floating-panel,.elo-pet-ui-guard [data-elo-pet-entry]{display:none!important}
.elo-store-card{content-visibility:auto;contain-intrinsic-size:76px;contain:layout paint style}.elo-home-panel{contain:layout paint style}
#profile-modal .overflow-y-auto>*{content-visibility:auto;contain-intrinsic-size:140px;contain:layout paint style}
.elo-chat-message{content-visibility:auto;contain-intrinsic-size:74px;contain:layout style}
#main-content[data-elo-fluid-tab="quests"] .bg-slate-900.rounded-2xl,#main-content[data-elo-fluid-tab="inventory"] .bg-slate-900.rounded-2xl,#main-content[data-elo-fluid-tab="friends"] .bg-slate-900.rounded-2xl{content-visibility:auto;contain-intrinsic-size:96px}
body.elo-ui-busy #elo-theme-fx .elo-space-particle,body.elo-ui-busy #elo-theme-fx::after,body.elo-scroll-busy #elo-theme-fx .elo-space-particle,body.elo-scroll-busy #elo-theme-fx::after,body.elo-input-active #elo-theme-fx .elo-space-particle,body.elo-input-active #elo-theme-fx::after{animation-play-state:paused!important}
#main-nav .nav-btn{touch-action:manipulation}.elo-nav-pressed{transform:scale(.94)!important;opacity:.9}
.elo-theme-celestial #elo-theme-fx{overflow:hidden;background-image:radial-gradient(ellipse at 18% 22%,rgba(56,189,248,.10),transparent 28%),radial-gradient(ellipse at 78% 68%,rgba(168,85,247,.13),transparent 34%),radial-gradient(ellipse at 48% 46%,rgba(59,130,246,.07),transparent 44%),linear-gradient(180deg,rgba(1,3,12,.18),rgba(2,6,23,.34))}
.elo-theme-celestial #elo-theme-fx::before{content:'';position:absolute;inset:-12%;pointer-events:none;opacity:.72;background-image:radial-gradient(circle,rgba(255,255,255,.95) 0 1px,transparent 1.5px),radial-gradient(circle,rgba(125,211,252,.75) 0 1px,transparent 1.4px),radial-gradient(circle,rgba(216,180,254,.70) 0 1px,transparent 1.3px);background-size:137px 137px,193px 193px,251px 251px;background-position:12px 24px,61px 17px,103px 89px;transform:rotate(-7deg)}
.elo-theme-celestial #elo-theme-fx::after{content:'';position:absolute;inset:-20%;pointer-events:none;opacity:.46;background:radial-gradient(ellipse at 22% 34%,rgba(59,130,246,.24),transparent 23%),radial-gradient(ellipse at 76% 61%,rgba(147,51,234,.25),transparent 26%),radial-gradient(ellipse at 52% 48%,rgba(14,165,233,.10),transparent 34%);filter:blur(18px);animation:eloCelestialDrift 34s ease-in-out infinite alternate;transform:rotate(-9deg) scale(1.08)}
@keyframes eloCelestialDrift{from{transform:rotate(-9deg) scale(1.08) translate3d(-1%,0,0)}to{transform:rotate(-5deg) scale(1.13) translate3d(2%,1%,0)}}
.elo-theme-celestial .elo-space-comet{animation:none!important;will-change:transform,opacity;transform-origin:center center}.elo-theme-celestial .elo-space-comet::before,.elo-theme-celestial .elo-space-comet::after{transform-origin:right center!important}
body:has(#profile-modal:not(.hidden)) #elo-theme-fx .elo-space-particle,body:has(#profile-modal:not(.hidden)) #elo-theme-fx::after,body:has(#generic-modal:not(.hidden)) #elo-theme-fx .elo-space-particle{animation-play-state:paused!important}
.elo-lite-device #profile-modal,.elo-lite-device .elo-admin-overlay,.elo-lite-device #generic-modal{backdrop-filter:none!important}.elo-lite-device .elo-theme-celestial #elo-theme-fx::after{filter:blur(8px);animation:none!important;opacity:.32}.elo-lite-device .elo-theme-celestial .elo-space-particle:nth-of-type(n+29){display:none!important}.elo-lite-device .elo-theme-celestial .elo-space-comet:nth-of-type(n+4){display:none!important}
`;
document.head.appendChild(css);

const toast=(text,type='info')=>{try{if(typeof window.showToast==='function')return window.showToast(text,type)}catch(_){}console.log('[Elo V36.11]',text)};
const uid=()=>state.user?.uid||'';
const coupleId=()=>window.coupleId||localStorage.getItem('elo_coupleId')||'';
const sandboxId=()=>`__admin_${uid()}`;
const sandboxPartnerId=()=>`__admin_partner_${uid()}`;
const isSandbox=()=>!!coupleId()&&coupleId()===sandboxId();
const ownedKey=()=>`elo_theme_owned_${uid()||'device'}`;
const themeKey=()=>`elo_theme_${uid()||'device'}`;
const safeOwned=()=>{try{return [...new Set(['akai',...JSON.parse(localStorage.getItem(ownedKey())||'[]')])]}catch(_){return ['akai']}};
const saveLocalAppearance=(appearance={})=>{const owned=[...new Set(['akai',...(Array.isArray(appearance.ownedThemes)?appearance.ownedThemes:[])])];localStorage.setItem(ownedKey(),JSON.stringify(owned.filter(x=>x!=='akai')));const selected=owned.includes(appearance.themeId)?appearance.themeId:'akai';localStorage.setItem(themeKey(),selected)};
const appearanceNow=()=>({ownedThemes:safeOwned(),themeId:localStorage.getItem(themeKey())||'akai'});
const appearanceSig=a=>JSON.stringify({ownedThemes:[...(a.ownedThemes||[])].sort(),themeId:a.themeId||'akai'});

async function pushAppearanceIfChanged(){if(!state.user||!state.themeReady||document.hidden)return;const current=appearanceNow(),sig=appearanceSig(current);if(sig===state.themeSignature)return;state.themeSignature=sig;try{await setDoc(doc(db,'userProfiles',uid()),{appearance:{...current,syncedAt:Date.now()}},{merge:true})}catch(e){console.warn('Theme sync:',e)}}
async function initThemeSync(user){const ref=doc(db,'userProfiles',user.uid),snap=await getDoc(ref),data=snap.exists()?snap.data():{},cloud=data.appearance;if(cloud&&Array.isArray(cloud.ownedThemes))saveLocalAppearance(cloud);else{const local=appearanceNow();await setDoc(ref,{appearance:{...local,syncedAt:Date.now()}},{merge:true})}state.themeSignature=appearanceSig(appearanceNow());state.themeReady=true;state.profileUnsub?.();state.profileUnsub=onSnapshot(ref,s=>{const a=s.data()?.appearance;if(!a||!Array.isArray(a.ownedThemes))return;const cloudSig=appearanceSig(a);if(cloudSig===state.themeSignature)return;saveLocalAppearance(a);state.themeSignature=appearanceSig(appearanceNow());try{window.applyEloTheme?.();window.updateUI?.()}catch(_){}},e=>console.warn('Theme profile listener:',e));installThemeHooks()}
function installThemeHooks(attempt=0){const original=window.selectEloTheme;if(typeof original==='function'&&!original.__eloV3611){const wrapped=async(...args)=>{const r=await original(...args);setTimeout(pushAppearanceIfChanged,80);return r};wrapped.__eloV3611=true;window.selectEloTheme=wrapped;return}if(attempt<30)setTimeout(()=>installThemeHooks(attempt+1),300)}

function addAdminFab(){if(document.getElementById('elo-admin-fab'))return;const b=document.createElement('button');b.id='elo-admin-fab';b.innerHTML='<span>◆</span> ADM';b.onclick=openAdminPanel;document.body.appendChild(b)}
function removeAdminFab(){document.getElementById('elo-admin-fab')?.remove();document.getElementById('elo-admin-overlay')?.remove();document.body.classList.remove('elo-admin-sandbox')}
async function ensureAdminSandbox(user){const sid=`__admin_${user.uid}`,pid=`__admin_partner_${user.uid}`,relRef=doc(db,'relationships',sid),profileRef=doc(db,'userProfiles',user.uid);try{const relSnap=await getDoc(relRef),rel=relSnap.exists()?relSnap.data():{},owner=rel.users?.[user.uid]||{},partner=rel.users?.[pid]||{};await setDoc(relRef,{isAdminSandbox:true,adminOwnerUid:user.uid,sandboxSolo:true,createdAt:rel.createdAt||Date.now(),users:{[user.uid]:{...owner,name:owner.name||user.displayName||'ADM',email:user.email||owner.email||'',photoUrl:user.photoURL||owner.photoUrl||'',coins:Number.isFinite(Number(owner.coins))?Number(owner.coins):10000,xp:Number(owner.xp||0),streak:Number(owner.streak||0)},[pid]:{...partner,name:'Parceiro de Teste',email:'',photoUrl:'',coins:Number.isFinite(Number(partner.coins))?Number(partner.coins):10000,xp:Number(partner.xp||0),streak:Number(partner.streak||0),isSandboxPartner:true}}},{merge:true});await setDoc(profileRef,{coupleId:sid,adminSandbox:{active:true,permanent:true,updatedAt:Date.now()}},{merge:true});const local=localStorage.getItem('elo_coupleId')||'';if(local!==sid){localStorage.setItem('elo_coupleId',sid);window.coupleId=sid;sessionStorage.setItem('elo_admin_bootstrap_reload','1');location.reload();return false}window.coupleId=sid;document.body?.classList.add('elo-admin-sandbox');sessionStorage.removeItem('elo_admin_bootstrap_reload');return true}catch(e){console.error('Sandbox ADM permanente:',e);toast('Não foi possível preparar o ambiente ADM.','error');return false}}
async function repairSandbox(){if(!state.isAdmin)return false;return ensureAdminSandbox(state.user)}
async function ensureAdminWebScreen(){if(!state.isAdmin||!isSandbox())return;await new Promise(r=>setTimeout(r,700));const authScreen=document.getElementById('auth-screen'),main=document.getElementById('main-content');if(authScreen&&!authScreen.classList.contains('hidden')&&main?.classList.contains('hidden')){if(sessionStorage.getItem('elo_admin_web_retry')!=='1'){sessionStorage.setItem('elo_admin_web_retry','1');location.reload()}else{sessionStorage.removeItem('elo_admin_web_retry');toast('Sandbox ADM carregado. Reabra a página se a interface não aparecer.','info')}}else sessionStorage.removeItem('elo_admin_web_retry')}

const GAME_BANKS={either:[['Praia 🏖️','Montanha 🏔️'],['Pizza 🍕','Hambúrguer 🍔'],['Filme 🎬','Série 📺'],['Viagem ✈️','Ficar em casa 🏠'],['Abraço 🤗','Beijo 💋'],['Planejar 📋','Improvisar 🎲'],['Doce 🍫','Salgado 🍟'],['Café ☕','Chá 🍵'],['Verão ☀️','Inverno ❄️'],['Cidade 🌆','Interior 🌿'],['Hotel 🏨','Cabana 🏕️'],['Dormir cedo 😴','Virar a noite 🌙'],['Cozinhar juntos 🍳','Pedir delivery 🛵'],['Foto 📸','Vídeo 🎥'],['Cinema 🍿','Streaming 🛋️'],['Presente surpresa 🎁','Escolher junto 🛍️'],['Rolê animado 🎉','Programa tranquilo 🕯️'],['Manhã ☀️','Noite 🌙'],['Maratona de série 📺','Jogar juntos 🎮'],['Sushi 🍣','Massa 🍝'],['Carro 🚗','Avião ✈️'],['Romance 💕','Comédia 😂'],['Organizar tudo ✅','Deixar acontecer ✨'],['Chuva 🌧️','Sol ☀️']],likely:[['','','esquecer onde colocou o celular?'],['','','planejar uma viagem surpresa?'],['','','rir no momento errado?'],['','','dormir durante um filme?'],['','','pedir desculpas primeiro?'],['','','gastar mais em um passeio?'],['','','chorar com um filme?'],['','','fazer uma surpresa romântica?'],['','','ficar com fome primeiro?'],['','','demorar mais para se arrumar?'],['','','tirar mais fotos do casal?'],['','','lembrar uma data importante?'],['','','querer adotar outro Pet?'],['','','começar uma guerra de cócegas?'],['','','cantar no carro?'],['','','roubar o cobertor?'],['','','dizer “eu avisei”?'],['','','escolher o restaurante?'],['','','comprar um mimo sem avisar?'],['','','planejar o próximo fim de semana?']],know:[['Doce 🍫','Salgado 🍟'],['Manhã ☀️','Noite 🌙'],['Sair 🎉','Ficar em casa 🏠'],['Presente 🎁','Experiência ✈️'],['Praia 🏖️','Piscina 🏊'],['Mensagem 💬','Ligação 📞'],['Café ☕','Chocolate quente 🍫'],['Filme de terror 👻','Comédia 😂'],['Viagem planejada 📋','Viagem improvisada 🎒'],['Restaurante 🍽️','Comida caseira 🍲'],['Foto espontânea 📸','Foto posada ✨'],['Dormir abraçado 🤗','Cada um no seu lado 😴'],['Aventura 🎢','Conforto 🛋️'],['Flores 🌷','Chocolate 🍫'],['Data especial 💕','Surpresa aleatória 🎁'],['Mar 🌊','Cachoeira 💦'],['Jantar 🍝','Café da manhã 🥐'],['Tênis 👟','Chinelo 🩴'],['Música alta 🔊','Música baixa 🎧'],['Organizar a casa 🧹','Deixar para depois 😅']]};
const gameRound=(mode,seq)=>{const bank=GAME_BANKS[mode]||GAME_BANKS.either;return bank[(Math.max(1,seq)-1)%bank.length]};
async function createExpandedGame(modeId='either',force=false){if(!coupleId()||!state.user)return;try{let selected=null;await runTransaction(db,async tx=>{const ref=doc(db,'relationships',coupleId()),snap=await tx.get(ref);if(!snap.exists())throw new Error('Elo não encontrado.');const data=snap.data(),existing=data.quickGame;if(existing&&existing.status==='open'&&!force){selected=existing;return}const seq=Math.max(0,Number(existing?.sequence||data.quickGameSequence||0))+1,round=gameRound(modeId,seq),pid=Object.keys(data.users||{}).find(x=>x!==uid());selected={id:`qg_${seq}_${modeId}`,sequence:seq,roundIndex:(seq-1)%(GAME_BANKS[modeId]?.length||1),mode:modeId,options:modeId==='likely'?[state.user.displayName||'Você',data.users?.[pid]?.name||'Seu amor']:round.slice(0,2),...(modeId==='likely'&&pid?{optionUserIds:[uid(),pid]}:{}),prompt:round[2]||'',choices:{},status:'open',createdAt:Date.now(),createdBy:uid()};tx.update(ref,{quickGame:selected,quickGameSequence:seq})});window.coupleData={...(window.coupleData||{}),quickGame:selected};setTimeout(()=>window.openCoupleGame?.(),40)}catch(e){console.error('Jogo expandido:',e);toast('Não foi possível criar a rodada.','error')}}
function installGameHooks(){const choose=window.chooseCoupleGame;if(typeof choose!=='function'||choose.__eloAdminWrapped)return false;window.newCoupleGame=(mode='either',force=false)=>createExpandedGame(mode,force);const originalChoose=choose.bind(window);const wrapped=async(index,expected='')=>{const r=await originalChoose(index,expected);if(state.isAdmin&&isSandbox())setTimeout(()=>adminAnswerGamePartner(expected||window.coupleData?.quickGame?.id),120);return r};wrapped.__eloAdminWrapped=true;window.chooseCoupleGame=wrapped;state.gameHooks=true;return true}
async function adminAnswerGamePartner(expectedId=''){if(!state.isAdmin||!isSandbox())return;const pid=sandboxPartnerId();try{await runTransaction(db,async tx=>{const ref=doc(db,'relationships',coupleId()),snap=await tx.get(ref);if(!snap.exists())return;const d=snap.data(),g=d.quickGame;if(!g||g.status==='done'||(expectedId&&g.id!==expectedId)||g.choices?.[pid]!==undefined)return;const myChoice=g.choices?.[uid()];if(myChoice===undefined)return;const partnerChoice=(Number(g.sequence||0)%3===0)?1-Number(myChoice):Number(myChoice),same=partnerChoice===Number(myChoice),now=Date.now(),choices={...(g.choices||{}),[pid]:partnerChoice};tx.update(ref,{'quickGame.choices':choices,'quickGame.status':'done','quickGame.finishedAt':now,'quickStats.rounds':increment(1),...(same?{'quickStats.matches':increment(1)}:{}),quickGameLastResult:{...g,choices,status:'done',finishedAt:now,seenBy:{[uid()]:true,[pid]:true}}})});setTimeout(()=>window.openCoupleGame?.(),80)}catch(e){console.warn('Resposta técnica do jogo:',e)}}

function missionRewardFromDom(questId){for(const el of document.querySelectorAll('[onclick]')){const a=el.getAttribute('onclick')||'';if(!a.includes(questId))continue;let card=el;for(let i=0;i<7&&card;i++,card=card.parentElement){const t=card.innerText||'',c=t.match(/\+(\d+)\s*Coins/i),x=t.match(/\+(\d+)\s*XP/i);if(c||x)return{reward:Number(c?.[1]||0),xp:Number(x?.[1]||0)}}}return{reward:0,xp:0}}
async function adminCompleteMission(questId){if(!state.isAdmin||!isSandbox()||!questId)return;const key=`${questId}_${uid()}`,rx=missionRewardFromDom(questId);try{let awarded=false;await runTransaction(db,async tx=>{const ref=doc(db,'relationships',coupleId()),snap=await tx.get(ref);if(!snap.exists())throw new Error('Elo não encontrado.');const d=snap.data(),current=d.quests?.[key];if(current==='completed')return;awarded=true;tx.update(ref,{[`quests.${key}`]:'completed',...(rx.reward?{[`users.${uid()}.coins`]:increment(rx.reward)}:{}),...(rx.xp?{[`users.${uid()}.xp`]:increment(rx.xp)}:{})})});try{window.closeGenericModal?.()}catch(_){}toast(awarded?`Missão concluída pelo ADM${rx.reward?` · +${rx.reward} Coins`:''}.`:'Essa missão já estava concluída.',awarded?'success':'info')}catch(e){console.error('Missão ADM:',e);toast('Não foi possível concluir a missão de teste.','error')}}
function installMissionHooks(){const request=window.requestQuestApproval,confirmFn=window.confirmQuestCompletion;if(typeof request==='function'&&!request.__eloAdminWrapped){const original=request.bind(window);const wrapped=questId=>state.isAdmin&&isSandbox()?adminCompleteMission(questId):original(questId);wrapped.__eloAdminWrapped=true;window.requestQuestApproval=wrapped}if(typeof confirmFn==='function'&&!confirmFn.__eloAdminWrapped){const original=confirmFn.bind(window);const wrapped=questId=>state.isAdmin&&isSandbox()?adminCompleteMission(questId):original(questId);wrapped.__eloAdminWrapped=true;window.confirmQuestCompletion=wrapped}state.missionHooks=!!window.requestQuestApproval?.__eloAdminWrapped;return state.missionHooks}

async function adminAcceptPetProposal(){if(!state.isAdmin||!isSandbox())return;try{await runTransaction(db,async tx=>{const ref=doc(db,'relationships',coupleId()),snap=await tx.get(ref);if(!snap.exists())throw new Error('elo');const data=snap.data(),p=data.petEggProposal;if(!p)return;const updates={};for(const[who,raw]of Object.entries(p.contributions||{})){const amount=Number(raw||0),balance=Number(data.users?.[who]?.coins||0);if(balance<amount)throw new Error('coins');if(amount>0)updates[`users.${who}.coins`]=balance-amount}updates[`petEggInventory.${p.eggType}`]=Number(data.petEggInventory?.[p.eggType]||0)+1;updates.petEggProposal=deleteField();tx.update(ref,updates)});toast('Parceiro técnico aprovou o ovo.','success');setTimeout(()=>window.openEggInventory?.(),120)}catch(e){console.error(e);toast(e?.message==='coins'?'Saldo insuficiente para concluir o teste.':'Não foi possível aprovar a proposta.','error')}}
async function adminResolveVouchers(){if(!state.isAdmin||!isSandbox())return;try{const q=query(collection(db,'relationships',coupleId(),'messages'),orderBy('timestamp','desc'),limit(120)),snap=await getDocs(q),targets=snap.docs.filter(d=>['pending','awaiting_confirmation'].includes(d.data()?.voucher?.status));if(!targets.length)return toast('Nenhum voucher pendente encontrado.','info');await runTransaction(db,async tx=>{const relRef=doc(db,'relationships',coupleId()),relSnap=await tx.get(relRef);if(!relSnap.exists())return;const ids=new Set();for(const m of targets){const data=m.data();if(data.voucher?.invId)ids.add(data.voucher.invId);tx.update(m.ref,{'voucher.status':'completed','voucher.completedAt':Date.now(),'voucher.confirmedByAdmin':true})}const inventory=(relSnap.data().inventory||[]).map(i=>ids.has(i.id)?{...i,status:'used',usedAt:Date.now(),confirmedByAdmin:true}:i);tx.update(relRef,{inventory})});toast(`${targets.length} voucher${targets.length>1?'s':''} concluído${targets.length>1?'s':''} pelo parceiro técnico.`,'success')}catch(e){console.error(e);toast('Não foi possível concluir os vouchers de teste.','error')}}
async function adminSendPartnerMessage(){if(!state.isAdmin||!isSandbox())return;try{const ref=doc(collection(db,'relationships',coupleId(),'messages')),now=Date.now();await setDoc(ref,{id:ref.id,senderId:sandboxPartnerId(),recipientUid:uid(),type:'text',text:'Mensagem de teste enviada pelo parceiro técnico 🤖',timestamp:now,reactions:{},readBy:{[sandboxPartnerId()]:true}});toast('Parceiro técnico enviou uma mensagem.','success')}catch(e){console.error(e);toast('Não foi possível enviar a mensagem técnica.','error')}}

function adminHtml(){return `<div id="elo-admin-overlay" class="elo-admin-overlay" onclick="if(event.target===this)this.remove()"><div class="elo-admin-panel"><div class="elo-admin-head"><div><span class="elo-admin-badge">AMBIENTE ADM PERMANENTE</span><h2>Painel ADM · Elo V${VERSION}</h2></div><button class="elo-admin-btn" onclick="document.getElementById('elo-admin-overlay')?.remove()">Fechar</button></div><p class="elo-admin-note">Conta exclusiva de testes. No Web, PWA e APK ela entra sempre no mesmo Sandbox técnico.</p><div class="elo-admin-section"><h3>Elo Coins</h3><input id="elo-admin-coins" class="elo-admin-input" type="number" inputmode="numeric" placeholder="Valor personalizado, ex.: 500"><div class="elo-admin-grid"><button class="elo-admin-btn good" onclick="eloAdminCoins(100)">+100</button><button class="elo-admin-btn good" onclick="eloAdminCoins(1000)">+1000</button><button class="elo-admin-btn danger" onclick="eloAdminCoins(-100)">-100</button><button class="elo-admin-btn danger" onclick="eloAdminCoins(-1000)">-1000</button></div><button class="elo-admin-btn" style="width:100%;margin-top:8px" onclick="eloAdminCoins(Number(document.getElementById('elo-admin-coins')?.value||0))">Aplicar valor</button></div><div class="elo-admin-section"><h3>Simular parceiro</h3><div class="elo-admin-grid"><button class="elo-admin-btn good" onclick="eloAdminAnswerGame()">Responder jogo atual</button><button class="elo-admin-btn good" onclick="eloAdminAcceptPetProposal()">Aprovar ovo</button><button class="elo-admin-btn good" onclick="eloAdminResolveVouchers()">Concluir vouchers</button><button class="elo-admin-btn good" onclick="eloAdminSendPartnerMessage()">Enviar mensagem</button><button class="elo-admin-btn" onclick="eloAdminRepairSandbox()">Reparar Sandbox</button></div><p class="elo-admin-note" style="margin-top:8px">Nas Missões, tocar em concluir já finaliza e recompensa a conta ADM sem esperar aprovação.</p></div><div class="elo-admin-section"><h3>Limpeza</h3><div class="elo-admin-grid"><button class="elo-admin-btn" onclick="eloAdminResetThemes()">Resetar temas para Akai</button><button class="elo-admin-btn danger" onclick="eloAdminResetPet()">Remover Pets e ovos</button></div></div></div></div>`}
function openAdminPanel(){if(!state.isAdmin)return;document.getElementById('elo-admin-overlay')?.remove();document.body.insertAdjacentHTML('beforeend',adminHtml())}
window.openEloAdmin=openAdminPanel;window.eloAdminEnterSandbox=async()=>ensureAdminSandbox(state.user);window.eloAdminRepairSandbox=async()=>{const ok=await repairSandbox();if(ok)toast('Sandbox reparado.','success')};window.eloAdminAnswerGame=()=>adminAnswerGamePartner(window.coupleData?.quickGame?.id||'');window.eloAdminAcceptPetProposal=adminAcceptPetProposal;window.eloAdminResolveVouchers=adminResolveVouchers;window.eloAdminSendPartnerMessage=adminSendPartnerMessage;
window.eloAdminCoins=async delta=>{if(!state.isAdmin||!Number.isFinite(delta)||delta===0)return;try{await updateDoc(doc(db,'relationships',coupleId()),{[`users.${uid()}.coins`]:increment(Math.trunc(delta))});toast(`${delta>0?'+':''}${Math.trunc(delta)} Elo Coins aplicado.`,'success')}catch(e){console.error(e);toast('Não foi possível alterar as moedas.','error')}};
window.eloAdminResetThemes=async()=>{if(!state.isAdmin||!confirm('Remover todos os temas comprados desta conta e voltar ao Akai?'))return;const appearance={ownedThemes:['akai'],themeId:'akai',syncedAt:Date.now(),resetByAdmin:true};try{saveLocalAppearance(appearance);state.themeSignature=appearanceSig(appearance);await setDoc(doc(db,'userProfiles',uid()),{appearance},{merge:true});window.applyEloTheme?.();toast('Temas de teste removidos.','success')}catch(e){console.error(e);toast('Falha ao resetar temas.','error')}};
window.eloAdminResetPet=async()=>{if(!state.isAdmin||!confirm('Remover Pet ativo, ovos, incubadora e coleção deste Sandbox?'))return;try{await updateDoc(doc(db,'relationships',coupleId()),{pet:deleteField(),petActiveId:deleteField(),petCollection:{},petEggProposal:deleteField(),petIncubator:deleteField(),petEggInventory:deleteField()});toast('Pets e ovos removidos.','success');syncPetUi()}catch(e){console.error(e);toast('Não foi possível remover os Pets.','error')}};

function hasPetJourney(){if(isSandbox())return true;const d=window.coupleData||{};return !!(d.pet||d.petActiveId||(d.petCollection&&Object.keys(d.petCollection).length)||(d.petEggInventory&&Object.values(d.petEggInventory||{}).some(v=>Number(v)>0))||d.petIncubator||d.petEggProposal)}
function syncPetUi(){if(!document.body)return;const auth=document.getElementById('auth-screen'),loginVisible=!!auth&&!auth.classList.contains('hidden'),show=!loginVisible&&hasPetJourney();document.body.classList.toggle('elo-pet-ui-guard',!show);document.querySelectorAll('[onclick*="openPetCenter"]').forEach(el=>{el.dataset.eloPetEntry='1';el.style.display=show?'':'none'});if(!show){document.querySelector('.elo-floating-pet')?.remove();document.querySelector('.elo-pet-floating-panel')?.remove()}}
function queuePetSync(){if(state.petSyncQueued)return;state.petSyncQueued=true;requestAnimationFrame(()=>{state.petSyncQueued=false;syncPetUi()})}
afterBody(()=>{syncPetUi();const observer=new MutationObserver(queuePetSync),auth=document.getElementById('auth-screen'),main=document.getElementById('main-content');if(auth)observer.observe(auth,{attributes:true,attributeFilter:['class']});if(main)observer.observe(main,{childList:true});setTimeout(syncPetUi,600)})

function markInteractionBusy(ms=180){if(!document.body)return;document.body.classList.add('elo-ui-busy');clearTimeout(window.__eloUiBusyTimer);window.__eloUiBusyTimer=setTimeout(()=>document.body?.classList.remove('elo-ui-busy'),ms)}
function tuneImages(root=document){const imgs=root instanceof HTMLImageElement?[root]:root.querySelectorAll?.('img')||[];let eager=0;for(const img of imgs){if(img.dataset.eloFluidImage==='1')continue;img.dataset.eloFluidImage='1';img.decoding='async';const critical=!!img.closest('#main-header,.elo-chat-header,#profile-modal .sticky,.elo-floating-pet')||eager<2;if(!critical&&!img.hasAttribute('loading'))img.loading='lazy';if(critical)eager++}}
function tuneMainContent(){const main=document.getElementById('main-content');if(!main)return;main.dataset.eloFluidTab=window.activeTab||'home';tuneImages(main)}
function queueDomTune(){if(state.domTuneQueued)return;state.domTuneQueued=true;requestAnimationFrame(()=>{state.domTuneQueued=false;tuneMainContent();tuneImages(document.getElementById('profile-modal')||document)})}
function installNavigationHook(attempt=0){const original=window.switchTab;if(typeof original!=='function'){if(attempt<30)setTimeout(()=>installNavigationHook(attempt+1),250);return false}if(original.__eloFluidWrapped){state.navHooks=true;return true}let lastTab='',lastAt=0;const wrapped=(tab,...args)=>{const now=performance.now();if(tab===lastTab&&now-lastAt<120&&window.activeTab===tab)return;lastTab=tab;lastAt=now;document.getElementById('main-content')?.setAttribute('data-elo-fluid-tab',tab||'home');markInteractionBusy(170);const result=original(tab,...args);requestAnimationFrame(queueDomTune);return result};wrapped.__eloFluidWrapped=true;window.switchTab=wrapped;state.navHooks=true;return true}
function installProfileHook(attempt=0){const open=window.openProfileModal,close=window.closeProfileModal;if(typeof open!=='function'){if(attempt<30)setTimeout(()=>installProfileHook(attempt+1),250);return false}if(!open.__eloFluidWrapped){const originalOpen=open.bind(window);const wrappedOpen=(...args)=>{markInteractionBusy(lowEndDevice?360:260);const r=originalOpen(...args);requestAnimationFrame(queueDomTune);return r};wrappedOpen.__eloFluidWrapped=true;window.openProfileModal=wrappedOpen}if(typeof close==='function'&&!close.__eloFluidWrapped){const originalClose=close.bind(window);const wrappedClose=(...args)=>{markInteractionBusy(140);return originalClose(...args)};wrappedClose.__eloFluidWrapped=true;window.closeProfileModal=wrappedClose}state.profileHooks=true;return true}
function installUiHooks(){if(state.uiHooks||!document.body)return;state.uiHooks=true;document.addEventListener('pointerdown',e=>{const nav=e.target.closest?.('#main-nav .nav-btn');if(nav){nav.classList.add('elo-nav-pressed');markInteractionBusy(190);setTimeout(()=>nav.classList.remove('elo-nav-pressed'),130);return}if(e.target.closest?.('[onclick*="openProfileModal"]'))markInteractionBusy(260)},{passive:true});document.addEventListener('focusin',e=>{if(e.target.matches?.('input,textarea,[contenteditable="true"]'))document.body.classList.add('elo-input-active')});document.addEventListener('focusout',e=>{if(e.target.matches?.('input,textarea,[contenteditable="true"]'))setTimeout(()=>{if(!document.activeElement?.matches?.('input,textarea,[contenteditable="true"]'))document.body.classList.remove('elo-input-active')},60)});document.addEventListener('scroll',e=>{const t=e.target;if(!(t instanceof Element)||(!t.closest?.('#main-content')&&!t.matches?.('#main-content,.elo-chat-messages,#profile-modal .overflow-y-auto')))return;document.body.classList.add('elo-scroll-busy');clearTimeout(state.scrollBusyTimer);state.scrollBusyTimer=setTimeout(()=>document.body?.classList.remove('elo-scroll-busy'),130)},{capture:true,passive:true});const main=document.getElementById('main-content');if(main){const observer=new MutationObserver(queueDomTune);observer.observe(main,{childList:true,subtree:true})}const profile=document.getElementById('profile-modal');if(profile){const observer=new MutationObserver(queueDomTune);observer.observe(profile,{childList:true,subtree:true,attributes:true,attributeFilter:['class']})}queueDomTune()}
function installFluidityHooks(){installUiHooks();installNavigationHook();installProfileHook();queueDomTune();const meta=document.querySelector('meta[name="elo-version"]');if(meta)meta.content=`${VERSION}-fluidity-phase-2`;document.documentElement.dataset.eloRuntimeVersion=VERSION}
function installRuntimeHooks(){installMissionHooks();installGameHooks();installThemeHooks();installFluidityHooks()}

function resetComet(el,index){const w=innerWidth,h=innerHeight,side=Math.random();let x,y,vx,vy;const speed=88+Math.random()*68;if(side<.42){x=-100;y=h*(.08+Math.random()*.72);vx=speed;vy=(Math.random()-.5)*28}else if(side<.84){x=w+100;y=h*(.08+Math.random()*.72);vx=-speed;vy=(Math.random()-.5)*28}else{x=w*(.08+Math.random()*.84);y=-90;vx=(Math.random()-.5)*42;vy=speed*.78}state.comets.set(el,{x,y,vx,vy,index,orbitBias:(Math.random()-.5)*.18});el.style.animation='none';el.style.opacity='.78'}
function isCelestialActive(){return !!document.body?.classList.contains('elo-theme-celestial')&&!!document.querySelector('.elo-black-hole')}
function heavyModalOpen(){const p=document.getElementById('profile-modal'),g=document.getElementById('generic-modal');return (!!p&&!p.classList.contains('hidden'))||(!!g&&!g.classList.contains('hidden'))||document.body?.classList.contains('elo-ui-busy')||document.body?.classList.contains('elo-scroll-busy')||document.body?.classList.contains('elo-input-active')}
function cometFrame(now){state.raf=0;if(document.hidden||!isCelestialActive())return;const tab=window.activeTab||'home',frameBudget=heavyModalOpen()?110:(lowEndDevice?(tab==='home'?40:64):(tab==='home'?26:46));if(now-state.lastPaint<frameBudget){state.raf=requestAnimationFrame(cometFrame);return}state.lastPaint=now;const hole=document.querySelector('.elo-black-hole'),els=[...document.querySelectorAll('.elo-space-comet')].filter(el=>getComputedStyle(el).display!=='none');if(!hole||!els.length)return;const hr=hole.getBoundingClientRect(),hx=hr.left+hr.width/2,hy=hr.top+hr.height/2,dt=Math.min(.045,Math.max(.010,(now-(state.lastFrame||now))/1000));state.lastFrame=now;if(!heavyModalOpen())els.forEach((el,i)=>{if(!state.comets.has(el))resetComet(el,i);const p=state.comets.get(el);let dx=hx-p.x,dy=hy-p.y,r2=dx*dx+dy*dy,dist=Math.sqrt(r2)||1;const soft=82,G=lowEndDevice?550000:680000,a=Math.min(G/(r2+soft*soft),210),tangentX=-dy/dist*p.orbitBias*a,tangentY=dx/dist*p.orbitBias*a;p.vx+=(a*dx/dist+tangentX)*dt;p.vy+=(a*dy/dist+tangentY)*dt;const speed=Math.hypot(p.vx,p.vy),maxSpeed=lowEndDevice?270:315;if(speed>maxSpeed){p.vx=p.vx/speed*maxSpeed;p.vy=p.vy/speed*maxSpeed}p.x+=p.vx*dt;p.y+=p.vy*dt;const ang=Math.atan2(p.vy,p.vx)*180/Math.PI,near=Math.max(0,1-dist/300),stretch=1+near*.75;el.style.transform=`translate3d(${p.x}px,${p.y}px,0) rotate(${ang}deg) scaleX(${stretch})`;el.style.opacity=String(Math.max(.22,Math.min(1,.52+speed/500+near*.2)));if(dist<Math.max(24,hr.width*.105)||p.x<-190||p.x>innerWidth+190||p.y<-170||p.y>innerHeight+170)resetComet(el,i)});state.raf=requestAnimationFrame(cometFrame)}
function syncCelestialLoop(){if(document.hidden||!isCelestialActive()){if(state.raf)cancelAnimationFrame(state.raf);state.raf=0;state.comets.clear();return}if(!state.raf){state.lastFrame=performance.now();state.lastPaint=0;state.raf=requestAnimationFrame(cometFrame)}}
afterBody(()=>{const themeObserver=new MutationObserver(syncCelestialLoop);themeObserver.observe(document.body,{attributes:true,attributeFilter:['class','data-elo-tab']});document.addEventListener('visibilitychange',()=>{syncCelestialLoop();if(!document.hidden)pushAppearanceIfChanged()});syncCelestialLoop();installFluidityHooks();setTimeout(installFluidityHooks,900)})

async function checkAdmin(user){try{const s=await getDoc(doc(db,'admins',user.uid));state.isAdmin=!!(s.exists()&&s.data()?.enabled===true);state.adminDoc=s.exists()?s.data():null}catch(e){state.isAdmin=false;state.adminDoc=null;console.warn('ADM indisponível:',e)}window.ELO_V36_11.isAdmin=state.isAdmin;if(state.isAdmin){const ready=await ensureAdminSandbox(user);if(!ready)return;addAdminFab();await repairSandbox();installRuntimeHooks();setTimeout(installRuntimeHooks,800);setTimeout(installRuntimeHooks,2400);ensureAdminWebScreen()}else removeAdminFab();syncPetUi();syncCelestialLoop()}

onAuthStateChanged(auth,async user=>{state.user=user;state.themeReady=false;state.profileUnsub?.();state.profileUnsub=null;if(!user){removeAdminFab();syncPetUi();return}try{await initThemeSync(user)}catch(e){console.warn('Theme sync init:',e)}await checkAdmin(user);setTimeout(syncPetUi,250)});
console.info(`[Elo] V${VERSION} runtime carregado · ADM completo · fluidez fase 2.`);
