import { getApps, getApp, initializeApp } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, updateDoc, runTransaction, increment, deleteField, onSnapshot } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js';

const VERSION='36.11.2';
const firebaseConfig={apiKey:'AIzaSyAExc0XnqS2MjL3bTmvNNx2CnBbziiyJds',authDomain:'elo-app-82e6e.firebaseapp.com',projectId:'elo-app-82e6e',storageBucket:'elo-app-82e6e.firebasestorage.app',messagingSenderId:'107299510923',appId:'1:107299510923:web:eb9c8b550ba4ecb3bc528e'};
const app=getApps().length?getApp():initializeApp(firebaseConfig);
const auth=getAuth(app),db=getFirestore(app);
const state={user:null,isAdmin:false,adminDoc:null,themeSignature:'',themeReady:false,profileUnsub:null,comets:new Map(),raf:0,lastFrame:0,lastPaint:0,petSyncQueued:false};
window.ELO_V36_11={version:VERSION,isAdmin:false};

const lowEndDevice=(()=>{const cores=Number(navigator.hardwareConcurrency||4),memory=Number(navigator.deviceMemory||4);return cores<=4||memory<=4})();
if(lowEndDevice)document.documentElement.classList.add('elo-lite-device');

afterBody(()=>document.body.classList.add('elo-pet-ui-guard'));

const css=document.createElement('style');
css.textContent=`
#elo-admin-fab{position:fixed;right:14px;top:max(14px,env(safe-area-inset-top));z-index:2147483000;border:1px solid rgba(251,113,133,.45);background:rgba(15,23,42,.94);color:#fff;padding:9px 12px;border-radius:999px;font:900 10px/1 Inter,sans-serif;letter-spacing:.08em;box-shadow:0 12px 34px rgba(0,0,0,.4);backdrop-filter:blur(10px)}
#elo-admin-fab span{color:#fb7185}.elo-admin-overlay{position:fixed;inset:0;z-index:2147483500;background:rgba(2,6,23,.82);backdrop-filter:blur(8px);display:grid;place-items:end center;padding:12px}.elo-admin-panel{width:min(100%,460px);max-height:88dvh;overflow:auto;background:#0f172a;border:1px solid rgba(148,163,184,.2);border-radius:26px;padding:18px;color:#e2e8f0;box-shadow:0 28px 80px rgba(0,0,0,.55)}.elo-admin-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.elo-admin-head h2{font-size:18px;font-weight:900;color:white}.elo-admin-badge{display:inline-flex;padding:5px 8px;border-radius:999px;background:rgba(244,63,94,.13);color:#fb7185;font-size:9px;font-weight:900;letter-spacing:.12em}.elo-admin-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.elo-admin-btn{border:1px solid rgba(148,163,184,.16);background:#1e293b;color:white;border-radius:14px;padding:11px 10px;font-size:11px;font-weight:900}.elo-admin-btn:active{transform:scale(.97)}.elo-admin-btn.danger{border-color:rgba(244,63,94,.3);background:rgba(127,29,29,.22);color:#fecdd3}.elo-admin-btn.good{border-color:rgba(34,197,94,.28);background:rgba(20,83,45,.24);color:#bbf7d0}.elo-admin-section{padding:13px 0;border-top:1px solid rgba(148,163,184,.12)}.elo-admin-section:first-of-type{border-top:0}.elo-admin-section h3{font-size:10px;text-transform:uppercase;letter-spacing:.14em;color:#94a3b8;font-weight:900;margin-bottom:8px}.elo-admin-note{font-size:10px;color:#94a3b8;line-height:1.55}.elo-admin-input{width:100%;background:#020617;border:1px solid #334155;border-radius:12px;padding:11px;color:white;margin-bottom:8px}.elo-admin-sandbox::after{content:'MODO ADM';position:fixed;left:50%;top:max(8px,env(safe-area-inset-top));transform:translateX(-50%);z-index:2147482500;background:rgba(225,29,72,.9);color:#fff;padding:5px 9px;border-radius:999px;font:900 9px/1 Inter,sans-serif;letter-spacing:.14em;pointer-events:none}
.elo-pet-ui-guard .elo-floating-pet,.elo-pet-ui-guard .elo-pet-floating-panel,.elo-pet-ui-guard [data-elo-pet-entry]{display:none!important}
.elo-theme-celestial #elo-theme-fx{overflow:hidden;background-image:radial-gradient(ellipse at 18% 22%,rgba(56,189,248,.10),transparent 28%),radial-gradient(ellipse at 78% 68%,rgba(168,85,247,.13),transparent 34%),radial-gradient(ellipse at 48% 46%,rgba(59,130,246,.07),transparent 44%),linear-gradient(180deg,rgba(1,3,12,.18),rgba(2,6,23,.34))}
.elo-theme-celestial #elo-theme-fx::before{content:'';position:absolute;inset:-12%;pointer-events:none;opacity:.72;background-image:radial-gradient(circle,rgba(255,255,255,.95) 0 1px,transparent 1.5px),radial-gradient(circle,rgba(125,211,252,.75) 0 1px,transparent 1.4px),radial-gradient(circle,rgba(216,180,254,.70) 0 1px,transparent 1.3px);background-size:137px 137px,193px 193px,251px 251px;background-position:12px 24px,61px 17px,103px 89px;transform:rotate(-7deg)}
.elo-theme-celestial #elo-theme-fx::after{content:'';position:absolute;inset:-20%;pointer-events:none;opacity:.46;background:radial-gradient(ellipse at 22% 34%,rgba(59,130,246,.24),transparent 23%),radial-gradient(ellipse at 76% 61%,rgba(147,51,234,.25),transparent 26%),radial-gradient(ellipse at 52% 48%,rgba(14,165,233,.10),transparent 34%);filter:blur(18px);animation:eloCelestialDrift 34s ease-in-out infinite alternate;transform:rotate(-9deg) scale(1.08)}
@keyframes eloCelestialDrift{from{transform:rotate(-9deg) scale(1.08) translate3d(-1%,0,0)}to{transform:rotate(-5deg) scale(1.13) translate3d(2%,1%,0)}}
.elo-theme-celestial .elo-space-comet{animation:none!important;will-change:transform,opacity;transform-origin:center center}.elo-theme-celestial .elo-space-comet::before,.elo-theme-celestial .elo-space-comet::after{transform-origin:right center!important}
body:has(#profile-modal:not(.hidden)) #elo-theme-fx .elo-space-particle,body:has(#profile-modal:not(.hidden)) #elo-theme-fx::after,body:has(#generic-modal:not(.hidden)) #elo-theme-fx .elo-space-particle{animation-play-state:paused!important}
.elo-lite-device #profile-modal,.elo-lite-device .elo-admin-overlay{backdrop-filter:none!important}
.elo-lite-device .elo-theme-celestial #elo-theme-fx::after{filter:blur(8px);animation:none!important;opacity:.32}
.elo-lite-device .elo-theme-celestial .elo-space-particle:nth-of-type(n+29){display:none!important}
.elo-lite-device .elo-theme-celestial .elo-space-comet:nth-of-type(n+4){display:none!important}
`;
document.head.appendChild(css);

function afterBody(fn){if(document.body)fn();else document.addEventListener('DOMContentLoaded',fn,{once:true})}
const toast=(text,type='info')=>{try{if(typeof window.showToast==='function')return window.showToast(text,type)}catch(_){} console.log('[Elo V36.11]',text)};
const uid=()=>state.user?.uid||'';
const coupleId=()=>window.coupleId||localStorage.getItem('elo_coupleId')||'';
const ownedKey=()=>`elo_theme_owned_${uid()||'device'}`;
const themeKey=()=>`elo_theme_${uid()||'device'}`;
const safeOwned=()=>{try{return [...new Set(['akai',...JSON.parse(localStorage.getItem(ownedKey())||'[]')])]}catch(_){return ['akai']}};
const saveLocalAppearance=(appearance={})=>{const owned=[...new Set(['akai',...(Array.isArray(appearance.ownedThemes)?appearance.ownedThemes:[])])];localStorage.setItem(ownedKey(),JSON.stringify(owned.filter(x=>x!=='akai')));const selected=owned.includes(appearance.themeId)?appearance.themeId:'akai';localStorage.setItem(themeKey(),selected)};
const appearanceNow=()=>({ownedThemes:safeOwned(),themeId:localStorage.getItem(themeKey())||'akai'});
const appearanceSig=a=>JSON.stringify({ownedThemes:[...(a.ownedThemes||[])].sort(),themeId:a.themeId||'akai'});

async function pushAppearanceIfChanged(){if(!state.user||!state.themeReady||document.hidden)return;const current=appearanceNow(),sig=appearanceSig(current);if(sig===state.themeSignature)return;state.themeSignature=sig;try{await setDoc(doc(db,'userProfiles',uid()),{appearance:{...current,syncedAt:Date.now()}},{merge:true})}catch(e){console.warn('V36.11 theme sync',e)}}
async function initThemeSync(user){const ref=doc(db,'userProfiles',user.uid),snap=await getDoc(ref),data=snap.exists()?snap.data():{},cloud=data.appearance;if(cloud&&Array.isArray(cloud.ownedThemes))saveLocalAppearance(cloud);else{const local=appearanceNow();await setDoc(ref,{appearance:{...local,syncedAt:Date.now()}},{merge:true})}state.themeSignature=appearanceSig(appearanceNow());state.themeReady=true;state.profileUnsub?.();state.profileUnsub=onSnapshot(ref,s=>{const a=s.data()?.appearance;if(!a||!Array.isArray(a.ownedThemes))return;const cloudSig=appearanceSig(a);if(cloudSig===state.themeSignature)return;saveLocalAppearance(a);state.themeSignature=appearanceSig(appearanceNow())},e=>console.warn('Theme profile listener:',e));installThemeHooks()}
function installThemeHooks(attempt=0){const original=window.selectEloTheme;if(typeof original==='function'&&!original.__eloV3611){const wrapped=async(...args)=>{const r=await original(...args);setTimeout(pushAppearanceIfChanged,80);return r};wrapped.__eloV3611=true;window.selectEloTheme=wrapped;return}if(attempt<15)setTimeout(()=>installThemeHooks(attempt+1),400)}

function addAdminFab(){if(document.getElementById('elo-admin-fab'))return;const b=document.createElement('button');b.id='elo-admin-fab';b.innerHTML='<span>◆</span> ADM';b.onclick=openAdminPanel;document.body.appendChild(b)}
function removeAdminFab(){document.getElementById('elo-admin-fab')?.remove();document.getElementById('elo-admin-overlay')?.remove();document.body.classList.remove('elo-admin-sandbox')}
const sandboxId=()=>`__admin_${uid()}`;
const sandboxPartnerId=()=>`__admin_partner_${uid()}`;
const isSandbox=()=>!!coupleId()&&coupleId()===sandboxId();

async function ensureAdminSandbox(user){
 const sid=`__admin_${user.uid}`,pid=`__admin_partner_${user.uid}`,relRef=doc(db,'relationships',sid),profileRef=doc(db,'userProfiles',user.uid);
 try{
  const relSnap=await getDoc(relRef),rel=relSnap.exists()?relSnap.data():{},owner=rel.users?.[user.uid]||{},partner=rel.users?.[pid]||{};
  await setDoc(relRef,{isAdminSandbox:true,adminOwnerUid:user.uid,sandboxSolo:true,createdAt:rel.createdAt||Date.now(),users:{[user.uid]:{...owner,name:owner.name||user.displayName||'ADM',email:user.email||owner.email||'',photoUrl:user.photoURL||owner.photoUrl||'',coins:Number.isFinite(Number(owner.coins))?Number(owner.coins):10000,xp:Number(owner.xp||0),streak:Number(owner.streak||0)},[pid]:{...partner,name:'Parceiro de Teste',email:'',photoUrl:'',coins:Number.isFinite(Number(partner.coins))?Number(partner.coins):10000,xp:Number(partner.xp||0),streak:Number(partner.streak||0),isSandboxPartner:true}}},{merge:true});
  await setDoc(profileRef,{coupleId:sid,adminSandbox:{active:true,permanent:true,updatedAt:Date.now()}},{merge:true});
  const local=localStorage.getItem('elo_coupleId')||'';
  if(local!==sid||window.coupleId!==sid){localStorage.setItem('elo_coupleId',sid);window.coupleId=sid;location.reload();return false}
  document.body?.classList.add('elo-admin-sandbox');return true;
 }catch(e){console.error('Sandbox ADM permanente:',e);toast('Não foi possível preparar o ambiente ADM.','error');return false}
}

async function checkAdmin(user){try{const s=await getDoc(doc(db,'admins',user.uid));state.isAdmin=!!(s.exists()&&s.data()?.enabled===true);state.adminDoc=s.exists()?s.data():null}catch(e){state.isAdmin=false;state.adminDoc=null;console.warn('ADM indisponível:',e)}window.ELO_V36_11.isAdmin=state.isAdmin;if(state.isAdmin){const ready=await ensureAdminSandbox(user);if(!ready)return;addAdminFab();await repairSandbox();installMissionHook()}else removeAdminFab();syncPetUi();syncCelestialLoop()}

async function repairSandbox(){if(!state.isAdmin||!isSandbox())return ensureAdminSandbox(state.user)}

function adminHtml(){return `<div id="elo-admin-overlay" class="elo-admin-overlay" onclick="if(event.target===this)this.remove()"><div class="elo-admin-panel"><div class="elo-admin-head"><div><span class="elo-admin-badge">AMBIENTE ADM PERMANENTE</span><h2>Painel ADM · Elo V${VERSION}</h2></div><button class="elo-admin-btn" onclick="document.getElementById('elo-admin-overlay')?.remove()">Fechar</button></div><p class="elo-admin-note">Esta conta é exclusivamente de testes. Ela sempre entra no Sandbox e nunca precisa criar ou entrar em um Elo real.</p><div class="elo-admin-section"><h3>Elo Coins</h3><input id="elo-admin-coins" class="elo-admin-input" type="number" inputmode="numeric" placeholder="Valor personalizado, ex.: 500"><div class="elo-admin-grid"><button class="elo-admin-btn good" onclick="eloAdminCoins(100)">+100</button><button class="elo-admin-btn good" onclick="eloAdminCoins(1000)">+1000</button><button class="elo-admin-btn danger" onclick="eloAdminCoins(-100)">-100</button><button class="elo-admin-btn danger" onclick="eloAdminCoins(-1000)">-1000</button></div><button class="elo-admin-btn" style="width:100%;margin-top:8px" onclick="eloAdminCoins(Number(document.getElementById('elo-admin-coins')?.value||0))">Aplicar valor</button></div><div class="elo-admin-section"><h3>Testes e limpeza</h3><div class="elo-admin-grid"><button class="elo-admin-btn" onclick="eloAdminResetThemes()">Resetar temas para Akai</button><button class="elo-admin-btn danger" onclick="eloAdminResetPet()">Remover Pets e ovos</button></div><p class="elo-admin-note" style="margin-top:8px">O parceiro técnico existe somente para liberar recursos de casal. Missões continuam sendo autoaprovadas para a conta ADM.</p></div></div></div>`}
function openAdminPanel(){if(!state.isAdmin)return;document.getElementById('elo-admin-overlay')?.remove();document.body.insertAdjacentHTML('beforeend',adminHtml())}
window.openEloAdmin=openAdminPanel;
window.eloAdminEnterSandbox=async()=>ensureAdminSandbox(state.user);

window.eloAdminCoins=async delta=>{if(!state.isAdmin||!Number.isFinite(delta)||delta===0)return;const cid=coupleId();if(!cid)return toast('Sandbox ainda não está pronto.','error');try{await updateDoc(doc(db,'relationships',cid),{[`users.${uid()}.coins`]:increment(Math.trunc(delta))});toast(`${delta>0?'+':''}${Math.trunc(delta)} Elo Coins aplicado.`,'success')}catch(e){console.error(e);toast('Não foi possível alterar as moedas.','error')}};
window.eloAdminResetThemes=async()=>{if(!state.isAdmin)return;if(!confirm('Remover todos os temas comprados desta conta ADM e voltar ao Akai?'))return;const appearance={ownedThemes:['akai'],themeId:'akai',syncedAt:Date.now(),resetByAdmin:true};try{saveLocalAppearance(appearance);state.themeSignature=appearanceSig(appearance);await setDoc(doc(db,'userProfiles',uid()),{appearance},{merge:true});toast('Temas de teste removidos.','success')}catch(e){console.error(e);toast('Falha ao resetar temas.','error')}};
window.eloAdminResetPet=async()=>{if(!state.isAdmin)return;const cid=coupleId();if(!cid)return;if(!confirm('Isso removerá Pet ativo, ovos e coleção de Pets do Sandbox. Continuar?'))return;try{await updateDoc(doc(db,'relationships',cid),{pet:deleteField(),petActiveId:deleteField(),petCollection:{},petEggProposal:deleteField(),petIncubator:deleteField(),petEggInventory:deleteField()});toast('Pets e ovos removidos do Sandbox.','success');syncPetUi()}catch(e){console.error(e);toast('Não foi possível remover os Pets.','error')}};

function missionRewardFromDom(questId){for(const el of document.querySelectorAll('[onclick]')){const a=el.getAttribute('onclick')||'';if(!a.includes(questId))continue;let card=el;for(let i=0;i<6&&card;i++,card=card.parentElement){const t=card.innerText||'';const c=t.match(/\+(\d+)\s*Coins/i),x=t.match(/\+(\d+)\s*XP/i);if(c||x)return{reward:Number(c?.[1]||0),xp:Number(x?.[1]||0)}}}return{reward:0,xp:0}}
async function autoApproveMission(questId,reward,xp){if(!state.isAdmin||!isSandbox())return;const cid=coupleId(),key=`${questId}_${uid()}`;try{await new Promise(r=>setTimeout(r,180));await runTransaction(db,async tx=>{const ref=doc(db,'relationships',cid),snap=await tx.get(ref);if(!snap.exists())return;const d=snap.data();if(d.quests?.[key]!=='pending_approval')return;tx.update(ref,{[`quests.${key}`]:'completed',[`users.${uid()}.coins`]:increment(reward),[`users.${uid()}.xp`]:increment(xp)})});toast(`Missão autoaprovada${reward?` · +${reward} Coins`:''}.`,'success')}catch(e){console.warn('Autoaprovação ADM:',e)}}
function installMissionHook(){if(window.__eloAdminMissionHook)return;let attempts=0;const tryHook=()=>{if(typeof window.confirmQuestCompletion!=='function'){if(attempts++<20)setTimeout(tryHook,400);return}if(window.__eloAdminMissionHook)return;const original=window.confirmQuestCompletion.bind(window);window.confirmQuestCompletion=async questId=>{const rx=missionRewardFromDom(questId),result=await original(questId);if(isSandbox())autoApproveMission(questId,rx.reward,rx.xp);return result};window.__eloAdminMissionHook=true};tryHook()}

function hasPetJourney(){if(isSandbox())return true;const d=window.coupleData||{};return !!(d.pet||d.petActiveId||(d.petCollection&&Object.keys(d.petCollection).length)||(d.petEggInventory&&((Array.isArray(d.petEggInventory)&&d.petEggInventory.length)||Object.keys(d.petEggInventory||{}).length))||d.petIncubator||d.petEggProposal)}
function syncPetUi(){if(!document.body)return;const authScreen=document.getElementById('auth-screen'),loginVisible=!!authScreen&&!authScreen.classList.contains('hidden'),show=!loginVisible&&hasPetJourney();document.body.classList.toggle('elo-pet-ui-guard',!show);document.querySelectorAll('[onclick*="openPetCenter"]').forEach(el=>{el.dataset.eloPetEntry='1';el.style.display=show?'':'none'});if(!show){document.querySelector('.elo-floating-pet')?.remove();document.querySelector('.elo-pet-floating-panel')?.remove()}}
function queuePetSync(){if(state.petSyncQueued)return;state.petSyncQueued=true;requestAnimationFrame(()=>{state.petSyncQueued=false;syncPetUi()})}
afterBody(()=>{syncPetUi();const observer=new MutationObserver(queuePetSync);const authScreen=document.getElementById('auth-screen');if(authScreen)observer.observe(authScreen,{attributes:true,attributeFilter:['class']});observer.observe(document.body,{childList:true,subtree:false});setTimeout(syncPetUi,700)})

function resetComet(el,index){const w=innerWidth,h=innerHeight,side=Math.random();let x,y,vx,vy;const speed=88+Math.random()*68;if(side<.42){x=-100;y=h*(.08+Math.random()*.72);vx=speed;vy=(Math.random()-.5)*28}else if(side<.84){x=w+100;y=h*(.08+Math.random()*.72);vx=-speed;vy=(Math.random()-.5)*28}else{x=w*(.08+Math.random()*.84);y=-90;vx=(Math.random()-.5)*42;vy=speed*.78}state.comets.set(el,{x,y,vx,vy,index,orbitBias:(Math.random()-.5)*.18});el.style.animation='none';el.style.opacity='.78'}
function isCelestialActive(){return !!document.body?.classList.contains('elo-theme-celestial')&&!!document.querySelector('.elo-black-hole')}
function modalOpen(){const p=document.getElementById('profile-modal');return !!p&&!p.classList.contains('hidden')}
function cometFrame(now){state.raf=0;if(document.hidden||!isCelestialActive())return;const frameBudget=lowEndDevice?34:22;if(now-state.lastPaint<frameBudget){state.raf=requestAnimationFrame(cometFrame);return}state.lastPaint=now;const hole=document.querySelector('.elo-black-hole'),els=[...document.querySelectorAll('.elo-space-comet')].filter(el=>getComputedStyle(el).display!=='none');if(!hole||!els.length)return;const hr=hole.getBoundingClientRect(),hx=hr.left+hr.width/2,hy=hr.top+hr.height/2,dt=Math.min(.045,Math.max(.010,(now-(state.lastFrame||now))/1000));state.lastFrame=now;if(!modalOpen())els.forEach((el,i)=>{if(!state.comets.has(el))resetComet(el,i);const p=state.comets.get(el);let dx=hx-p.x,dy=hy-p.y,r2=dx*dx+dy*dy,dist=Math.sqrt(r2)||1;const soft=82,G=lowEndDevice?560000:690000;let a=Math.min(G/(r2+soft*soft),215);const tangentX=-dy/dist*p.orbitBias*a,tangentY=dx/dist*p.orbitBias*a;p.vx+=(a*dx/dist+tangentX)*dt;p.vy+=(a*dy/dist+tangentY)*dt;const speed=Math.hypot(p.vx,p.vy),maxSpeed=lowEndDevice?275:320;if(speed>maxSpeed){p.vx=p.vx/speed*maxSpeed;p.vy=p.vy/speed*maxSpeed}p.x+=p.vx*dt;p.y+=p.vy*dt;const ang=Math.atan2(p.vy,p.vx)*180/Math.PI,near=Math.max(0,1-dist/300),stretch=1+near*.75;el.style.transform=`translate3d(${p.x}px,${p.y}px,0) rotate(${ang}deg) scaleX(${stretch})`;el.style.opacity=String(Math.max(.22,Math.min(1,.52+speed/500+near*.2)));el.style.filter=near>.35?`drop-shadow(0 0 ${4+near*8}px rgba(125,211,252,${.28+near*.28}))`:'';if(dist<Math.max(24,hr.width*.105)||p.x<-190||p.x>innerWidth+190||p.y<-170||p.y>innerHeight+170)resetComet(el,i)});state.raf=requestAnimationFrame(cometFrame)}
function syncCelestialLoop(){if(document.hidden||!isCelestialActive()){if(state.raf)cancelAnimationFrame(state.raf);state.raf=0;state.comets.clear();return}if(!state.raf){state.lastFrame=performance.now();state.lastPaint=0;state.raf=requestAnimationFrame(cometFrame)}}
afterBody(()=>{const themeObserver=new MutationObserver(syncCelestialLoop);themeObserver.observe(document.body,{attributes:true,attributeFilter:['class']});document.addEventListener('visibilitychange',()=>{syncCelestialLoop();if(!document.hidden)pushAppearanceIfChanged()});syncCelestialLoop()})

onAuthStateChanged(auth,async user=>{state.user=user;state.themeReady=false;state.profileUnsub?.();state.profileUnsub=null;if(!user){removeAdminFab();syncPetUi();return}try{await initThemeSync(user)}catch(e){console.warn('Theme sync init:',e)}await checkAdmin(user);setTimeout(syncPetUi,250)});
setInterval(()=>{if(!document.hidden){pushAppearanceIfChanged();syncPetUi()}},15000);
console.info(`[Elo] V${VERSION} runtime carregado · ${lowEndDevice?'perfil leve':'perfil completo'}.`);
